source: src
destination: _site
title: Dewy
url: https://dewy.io
description: Take back Drupal with Dewy, a service that lets you know what your Drupal sites are doing at your higher-ed institution, multi-site organization or digital agency.
shortDescription: A service that lets you know what your Drupal sites are doing at your higher-ed institution, multi-site organization or digital agency.
moduleURL: /module/dewy-7.x-1.0-beta3.tar.gz
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:title/